import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;


const arista = localFont({
  src: [
    {
      path: "../public/fonts/Arista-Pro-Light-trial.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Arista-Pro-Bold-trial.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Arista-Pro-Fat-trial.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-myfont",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arista.className} antialiased bg-darkgray min-h-screen`}
      >
        <div className="w-full h-full bg-smiles bg-repeat bg-sm">
          {children}
        </div>
      </body>
    </html>
  );
}
